import type { State } from "./types";

// 示例遗址：三个相邻探方，T0203↔T0204、T0204↔T0301 两段接界。
// 地层由各探方自行编号；接界处高程有的对得上，有的差 > 2cm 进待复核；
// H12、G1 跨接界；T0203 当前断网，本机已暂存一批观察。
export function makeSeed(): State {
  return {
    role: "reviewer",
    seq: 100,
    squares: [
      { id: "T0203", label: "西排探方", online: false },
      { id: "T0204", label: "中部探方", online: true },
      { id: "T0301", label: "东排探方", online: true },
    ],
    strata: [
      {
        id: "s-0203-1",
        squareId: "T0203",
        code: "第2层",
        top: 47.285,
        bottom: 46.912,
        soil: "黄褐土，较致密",
        confirmed: true,
        history: [],
      },
      {
        id: "s-0203-2",
        squareId: "T0203",
        code: "第3层",
        top: 46.912,
        bottom: 46.355,
        soil: "灰褐土，含陶片",
        confirmed: true,
        history: [],
      },
      {
        id: "s-0204-1",
        squareId: "T0204",
        code: "②层",
        top: 47.29,
        bottom: 46.905,
        soil: "黄褐土",
        confirmed: false,
        history: [],
      },
      {
        id: "s-0204-2",
        squareId: "T0204",
        code: "③层",
        top: 46.9, // 与 T0203 第3层顶差 1.2cm
        bottom: 46.333,
        soil: "灰褐土，夹炭屑",
        confirmed: false,
        history: [],
      },
      {
        id: "s-0301-1",
        squareId: "T0301",
        code: "②层",
        top: 47.25,
        bottom: 46.86,
        soil: "黄褐土，局部发红",
        confirmed: true,
        history: [],
      },
      {
        id: "s-0301-2",
        squareId: "T0301",
        code: "③层",
        top: 46.942,
        bottom: 46.401,
        soil: "灰褐淤土",
        confirmed: true,
        history: [],
      },
    ],
    notes: [],
    revisions: [
      {
        id: "rv-seed-1",
        stratumId: "s-0301-2",
        reason: "东壁接界处③层顶面向东抬升约4cm，疑G1沟壁挤压，建议修订顶高程",
        fromTop: 46.942,
        fromBottom: 46.401,
        toTop: 46.98,
        toBottom: 46.401,
        status: "pending",
        at: "2026-09-29 16:20",
        by: "field",
      },
    ],
    boundaries: [
      { id: "b-west", aSquareId: "T0203", bSquareId: "T0204", label: "T0203 东壁 × T0204 西壁" },
      { id: "b-east", aSquareId: "T0204", bSquareId: "T0301", label: "T0204 东壁 × T0301 西壁" },
    ],
    links: [
      // 接界线高程一致 → 已校核
      {
        id: "l-1",
        boundaryId: "b-west",
        aStratumId: "s-0203-1",
        bStratumId: "s-0204-1",
        elevA: 47.288,
        elevB: 47.288,
        updates: [],
      },
      // 差 2.6cm > 2cm → 待复核
      {
        id: "l-2",
        boundaryId: "b-west",
        aStratumId: "s-0203-2",
        bStratumId: "s-0204-2",
        elevA: 46.91,
        elevB: 46.936,
        updates: [],
      },
      // 差 3.5cm → 待复核
      {
        id: "l-3",
        boundaryId: "b-east",
        aStratumId: "s-0204-1",
        bStratumId: "s-0301-1",
        elevA: 47.29,
        elevB: 47.325,
        updates: [],
      },
      // 差 1.1cm → 已校核
      {
        id: "l-4",
        boundaryId: "b-east",
        aStratumId: "s-0204-2",
        bStratumId: "s-0301-2",
        elevA: 46.901,
        elevB: 46.912,
        updates: [],
      },
    ],
    units: [
      { id: "u-h12", kind: "灰坑", name: "H12", pointIds: ["p-h12-a", "p-h12-b"] },
      { id: "u-g1", kind: "沟状遗迹", name: "G1", pointIds: ["p-g1-a", "p-g1-b"] },
      { id: "u-f2", kind: "房址", name: "F2", pointIds: ["p-f2-1"] },
    ],
    points: {
      // H12 跨 T0203/T0204，且 l-2 待复核
      "p-h12-a": {
        id: "p-h12-a",
        unitId: "u-h12",
        squareId: "T0203",
        stratumId: "s-0203-2",
        text: "坑口压于第3层下，黑褐土，见动物骨",
        observer: "发掘队员·赵",
        at: "2026-09-28 10:12",
        finds: [
          { id: "f-1", name: "陶片", qty: 12, unit: "件" },
          { id: "f-2", name: "动物骨", qty: 3, unit: "件" },
        ],
        corrections: [],
      },
      "p-h12-b": {
        id: "p-h12-b",
        unitId: "u-h12",
        squareId: "T0204",
        stratumId: "s-0204-2",
        text: "同一灰坑向东延伸出方，夹炭屑",
        observer: "发掘队员·钱",
        at: "2026-09-28 11:05",
        finds: [{ id: "f-3", name: "炭样", qty: 1, unit: "袋" }],
        corrections: [],
      },
      // G1 跨 T0204/T0301：l-4 已对平，但 T0301 一侧被错记到②层 → 错层风险
      "p-g1-a": {
        id: "p-g1-a",
        unitId: "u-g1",
        squareId: "T0204",
        stratumId: "s-0204-2",
        text: "沟壁斜收，③层下开口",
        observer: "发掘队员·钱",
        at: "2026-09-29 09:40",
        finds: [],
        corrections: [],
      },
      "p-g1-b": {
        id: "p-g1-b",
        unitId: "u-g1",
        squareId: "T0301",
        stratumId: "s-0301-1",
        text: "西端入方，初判②层；现场怀疑应归③层",
        observer: "发掘队员·孙",
        at: "2026-09-29 09:55",
        finds: [],
        corrections: [],
      },
      "p-f2-1": {
        id: "p-f2-1",
        unitId: "u-f2",
        squareId: "T0301",
        stratumId: "s-0301-2",
        text: "夯土面，柱洞关系需复核",
        observer: "发掘队员·孙",
        at: "2026-09-27 15:22",
        finds: [],
        corrections: [],
      },
    },
    batches: [
      // T0203 断网期间本机暂存：一批仍在记录（草稿），一批已封口但上次回传失败
      {
        id: "batch-draft-1",
        clientBatchNo: "T0203-B03",
        squareId: "T0203",
        status: "draft",
        willFail: false,
        points: [
          {
            id: "p-offline-1",
            unitId: "u-h12",
            squareId: "T0203",
            stratumId: "s-0203-2",
            text: "断网补记：H12 西壁向内弧收，出方边缘含红烧土",
            observer: "发掘队员·赵",
            at: "2026-09-30 08:31",
            finds: [{ id: "f-4", name: "红烧土块", qty: 2, unit: "块" }],
            corrections: [],
          },
        ],
      },
      {
        id: "batch-failed-1",
        clientBatchNo: "T0203-B02",
        squareId: "T0203",
        status: "failed",
        willFail: true,
        error: "回传超时（HTTP 504）",
        points: [
          {
            id: "p-offline-2",
            unitId: "u-f2",
            squareId: "T0203",
            stratumId: "s-0203-2",
            text: "柱洞式遗迹向西伸入本排，暂并入 F2 观察",
            observer: "发掘队员·赵",
            at: "2026-09-29 17:02",
            finds: [],
            corrections: [],
          },
        ],
      },
    ],
    log: [
      {
        id: "log-seed-1",
        text: "批次 T0203-B02 回传失败：HTTP 504，已单独留存待重试",
        at: "2026-09-29 17:40",
        tone: "danger",
      },
      {
        id: "log-seed-2",
        text: "T0203 进入断网状态，观察点改为本机按批暂存",
        at: "2026-09-29 17:41",
        tone: "warn",
      },
      {
        id: "log-seed-3",
        text: "接界 b-west：第3层 × ③层 高程差 2.6cm，进入待复核",
        at: "2026-09-28 18:00",
        tone: "warn",
      },
    ],
  };
}
